server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: main-backend-route
          uri: lb://MAIN-BACKEND-SERVICE
          predicates:
            - Path=/api/auth/**, /api/business/**, /api/businesses/**, /api/chatbots/**, /api/documents/**, /api/customers/**, /api/conversations/**, /api/messages/**, /api/leads/**, /api/products/**, /api/dashboard/**, /api/public/chat/**
        - id: mcp-tool-route
          uri: lb://MCP-TOOL-SERVICE
          predicates:
            - Path=/api/mcp/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
